@startuml Relational Database

package "Data" {
    interface IDbConnectionFactory {
        + CreateConnection() : Task<IDbConnection>
    }

    class NpgsqlConnectionFactory {
        - _connectionString : string
    }

    class DbConstants {
        + DefaultConnectionPath : string
    }

    class DbInitializer {
        + Initialize(string connectionString) : void
    }
}

@enduml
