@startuml expense-tracker

package "Infrastructure" {
    !include data.puml
    !include data-access.puml
    !include business-logic.puml
    !include presentation.puml

    ' Relationships between layers
    
    ExpenseController --> IExpenseService
    IncomeController --> IIncomeService
    UserController --> IUserService

    IExpenseService ..> ExpenseResponse
    IExpenseService ..> ExpenseCreateRequest
    IExpenseService ..> ExpenseUpdateRequest

    IIncomeService ..> IncomeResponse
    IIncomeService ..> IncomeCreateRequest
    IIncomeService ..> IncomeUpdateRequest

    ExpenseService ..> IExpenseRepository
    IncomeService ..> IIncomeRepository
    UserService ..> IUserRepository

    ExpenseService ..|> IExpenseService
    IncomeService ..|> IIncomeService
    UserService ..|> IUserService

    UserRepository ..|> IUserRepository
    ExpenseRepository ..|> IExpenseRepository
    IncomeRepository ..|> IIncomeRepository

    IUserRepository ..> User
    IExpenseRepository ..> Expense
    IIncomeRepository ..> Income

    IUserRepository ..|> IBaseRepository
    IExpenseRepository ..|> IBaseRepository
    IIncomeRepository ..|> IBaseRepository

    ExpenseService --> IBudgetObserver : "AddObserver"

    ExpenseRepository --> IDatabaseStrategy
    IncomeRepository --> IDatabaseStrategy
    UserRepository --> IDatabaseStrategy

    DatabaseContext --> IDatabaseStrategy
    SQLDatabaseStrategy --> DatabaseContext
}

@enduml
