@startuml Presentation

package "Presentation Layer" {
    class ExpenseController {
        - expenseService: IExpenseService
        + GetExpenses() : Task<IActionResult>
        + GetExpenseById(Guid expenseId) : Task<IActionResult>
        + CreateExpense(UserCreateRequest user) : Task<IActionResult>
        + UpdateExpense(UserUpdateRequest user) : Task<IActionResult>
        + DeleteExpense(Guid expenseId) : Task<IActionResult>
    }

    class IncomeController {
        - incomeService: IIncomeService
        + GetIncomes() : Task<IActionResult>
        + GetIncomeById(Guid expenseId) : Task<IActionResult>
        + CreateIncome(ExpenseCreateRequest expense) : Task<IActionResult>
        + UpdateIncome(ExpenseUpdateRequest expense) : Task<IActionResult>
        + DeleteIncome(Guid expenseId) : Task<IActionResult>
    }

    class UserController {
        - userService: IUserService
        + RegisterUser() : Task<IActionResult>
        + LoginUser() : Task<IActionResult>
        + UpdateProfile() : Task<IActionResult>
        + ResetPassword() : Task<IActionResult>
    }
}

@enduml
